Refactor TWPCA API (work in progress)
ganguli-lab/twpca pull request #13
Opened 2017-06-22 16:56 UTC by ahwillia

The goal of this PR is to (a) simplify model initialization by pulling the helper functions in `warp.py` and `utils.py` into the main TWPCA class. In particular, the functions `generate_warps` and `compute_low_rank_factors` were beastly and referenced a ton of options that were internal to the TWPCA class anyways.

Also, the initialization for the factors and the warps are now decoupled from the `fit` function. Check out `TWPCA.assign_warps(...)` and `TWPCA.assign_factors(...)`. The user can now specify the warps directly - which is nice because e.g. you can specify warping functions that map from clock time to an animal's position on a 1D track.

I've also renamed variables to be more consistent. Pretty much everything with an underscore before it is a tensorflow variable, while the variable without the underscore is a numpy array.

I'd like to nail down a better option for tensorflow session management before merging. At the moment, this breaks the cross-validation code.

2017-06-22 18:04 UTC, nirum requested changes

2017-06-22 18:04 UTC, nirum commented on twpca/model.py
> +
add back 'identity'

2017-06-22 18:04 UTC, nirum commented on twpca/model.py
> +
create a separate graph in init and store it on self

2017-06-22 18:04 UTC, nirum commented on twpca/model.py
put code that creates tensorflow variables in a `with` block using `self._graph` as default

2017-06-22 18:04 UTC, nirum commented on twpca/model.py
> +        # Always include shift/scale with nonlinear transformation
add support for `identity` warptype

2017-06-22 20:47 UTC, ahwillia commented on twpca/model.py
> +
Done for now. But let's make a wrapper class to handle this!

2017-06-22 20:47 UTC, ahwillia commented on twpca/model.py
👍

2017-06-22 20:47 UTC, ahwillia commented on twpca/model.py
> +
Done.

2017-06-22 20:47 UTC, ahwillia commented on twpca/model.py
> +        # Always include shift/scale with nonlinear transformation
Done.

2017-06-22 20:54 UTC, ahwillia commented on twpca/model.py
> +# TODO - niru make a super class that handles graph and session management
@nirum - add your wrapper class here?

2017-06-23 00:16 UTC, poolio commented on twpca/model.py
> +        # TODO: better session management
remove

2017-06-23 00:16 UTC, poolio commented on twpca/model.py
> +    def fit(self, optimizer=tf.train.AdamOptimizer, niter=1000, lr=1e-3, sess=None, progressbar=True):
remove sess arg

2017-06-23 00:16 UTC, poolio commented on twpca/model.py
> +            _warp = self.tau_scale[:, None] * tf.cumsum(_pos_tau, 1) + self.tau_shift[:, None]
why prefix all these local variables with underscores?

2017-06-23 00:16 UTC, poolio commented on twpca/model.py
>                  to the neuron and time factors (default: False)
missing docstring for center_taus

2017-06-23 00:16 UTC, poolio commented on twpca/model.py
> +            self.tau = tf.get_variable('tau', shape=(self.n_trials, self.shared_length), dtype=tf.float32)
not super important, but why do we have these stored in both self._train_vars and self.tau (same for other params)

2017-06-23 00:16 UTC, poolio commented on twpca/model.py
> +                _warp = tf.clip_by_value(pin, 0, self.n_timepoints - 1)
add a TODO(ben): investigate clipping/boundary conditions

2017-06-23 00:16 UTC, poolio commented on twpca/model.py
> +            _args = [_warp, self.n_timepoints, self.shared_length]
why create this list?

2017-06-23 00:16 UTC, poolio commented on twpca/crossval.py
>      drop_prob (float) : probability of setting element of data to nan
add model_kw/fit_kw to docstring

2017-06-23 00:16 UTC, poolio commented on twpca/crossval.py
> +        model._sess.close()
you can also just do sess.close() here as it's a local variable

2017-06-23 00:16 UTC, poolio commented on twpca/crossval.py
> +                      model_kw=dict()):
don't have a mutable as a kwarg, set it to None and then assign it dict() if it is None

2017-06-23 00:16 UTC, poolio commented on twpca/crossval.py
> +        model_args = dict(n_components=nc,
`model_kwargs` as this is a dict?

2017-06-23 00:16 UTC, poolio commented on twpca/model.py
> +        self._lr = tf.placeholder(tf.float32, shape=[])
add doc here (or maybe at the top of the file?) that class variables prefixed with _ are TensorFlow Tensors

2017-06-23 00:16 UTC, poolio commented on twpca/model.py
> +        self.assign_train_op(optimizer)
rename this to `create_train_op`

2017-06-23 00:16 UTC, poolio commented on twpca/model.py
> +        self.assign_warps(warps, normalize_warps)
i would prefer `initialize_warps` and `initialize_factors` to `assign`

2017-06-23 00:16 UTC, poolio commented on twpca/model.py
> +        var_list = [v for k, v in self._train_vars.items() if k != 'warp'] + list(self._train_vars['warp'])
isn't this just the same as `self._train_vars.values()`?

2017-06-23 00:16 UTC, poolio commented on twpca/model.py
> +    def assign_warps(self, warps, normalize_warps=True):
`warps` should be `warps=None`

2017-06-23 00:16 UTC, poolio commented on twpca/utils.py
> +    return np.log(np.exp(y + 1e-5) - 1)
could you make this smaller, and maybe put it in the log, like:
`np.log(np.exp(y) - 1 + 1e-9)`

2017-06-23 00:29 UTC, ahwillia commented on twpca/crossval.py
> +        model_args = dict(n_components=nc,
its actually a mix of keyword and positional args...

2017-06-23 00:38 UTC, ahwillia commented on twpca/crossval.py
> +        model._sess.close()
oops, I didn't intend for sess to exist. Fixed now, good catch.

2017-06-23 00:39 UTC, merged