WIP: Cross-Validation Tools
ganguli-lab/twpca pull request #9
Opened 2017-03-31 18:27 UTC by ahwillia

This is my first pass at a set of cross-validation tools for twpca. The core code is in `twpca/crossval.py` and some rough examples are in `examples/crossval-demo/` (check out the notebooks in that folder).

Probably not ready to merge, still looking for feedback on the cross validation API and organization, as well as on the scope of the tools we want to offer is. For example, do we want to include plotting functions? (At the moment all the results are packaged into rather large and clunky dicts, and visualization would be helpful.)

2017-04-27 22:37 UTC, ahwillia commented
@poolio - this is ready for review. See `crossval-demo.ipynb` for usage.

![image](https://cloud.githubusercontent.com/assets/636625/25507154/4369d104-2b5f-11e7-9fa6-a2706b1e2f8b.png)

![image](https://cloud.githubusercontent.com/assets/636625/25507156/465aea92-2b5f-11e7-944c-e6fe040cd24a.png)

![image](https://cloud.githubusercontent.com/assets/636625/25507161/49557b18-2b5f-11e7-92a0-fd7357d08500.png)

2017-05-02 00:05 UTC, poolio reviewed
High level: great addition! It would be nice if we had options for cross-validation along any axis (time, neuron, trial) instead of just neurons.

Didn't get a chance to look at notebooks yet, will do a second pass for that tomorrow.

2017-05-02 00:05 UTC, poolio commented on twpca/crossval.py
> +def k_fold(N, K):
could we give these names like k_fold_iter or k_fold_iterator

2017-05-02 00:05 UTC, poolio commented on twpca/crossval.py
> +    idx = np.arange(N)
I would advocate for using additional randomness here, not just striding. An easy modification would be:
`idx = np.random.permutation(N)`

2017-05-02 00:05 UTC, poolio commented on twpca/crossval.py
> +    idx = np.arange(N)
`np.random.permutation` ?

2017-05-02 00:05 UTC, poolio commented on twpca/crossval.py
> +def leave_n_out(N, K):
change name to `leave_k_out` or change docstring and variable names below

2017-05-02 00:05 UTC, poolio commented on twpca/crossval.py
> +        K: int, crossvalidation parameter
missing max_crossval, fit_kw docstring

2017-05-02 00:05 UTC, poolio commented on twpca/crossval.py
> +        traindata = np.atleast_3d(data[:, :, train])
do you need the atleast_3d? it looks like train/test will always be lists

2017-05-02 00:05 UTC, poolio commented on twpca/crossval.py
> +        tf.reset_default_graph()
can you add a TODO(ben): better session management

2017-05-02 00:05 UTC, poolio commented on twpca/crossval.py
> +        # TODO - warmstart fits?
While this would speed things up, I think it would reduce the variability across runs, so might not be worth doing here.

2017-05-02 00:05 UTC, poolio commented on twpca/crossval.py
> +             'test_error': np.sum(resid) / len(testdata.ravel()),
have you checked that train/test error are computed the same?

2017-05-02 00:05 UTC, poolio commented on twpca/crossval.py
> +        _, resid, _, _ = np.linalg.lstsq(time_factors, testdata.reshape(-1, len(test)))
this should really be a function in the model, either transform() or apply() or something

2017-05-02 00:05 UTC, poolio commented on twpca/crossval.py
> +    """Performs cross-validation over number of components, warp regularization scale, and
add docstring here. what's expected format of fit_kw and model_kw? List of parameters that you're going to take the cross product over?

2017-05-02 00:05 UTC, poolio commented on twpca/crossval.py
> +    for nc, ws, ts in zip(tqdm(n_components), warp_scales, time_scales):
does this work? I think tqdm() expects an iterator and n_components is an integer

2017-05-02 00:05 UTC, poolio commented on twpca/crossval.py
> +    """Performs cross-validation over number of components, warp regularization scale, and
also it looks like warp_reg and time_reg have a weird expected format of functions that take a penalty amount as an argument, please doc!

2017-05-02 00:05 UTC, poolio commented on twpca/crossval.py
> +def err_per_component(data, component_range,
error_per_component?

2017-05-02 00:05 UTC, poolio commented on twpca/datasets.py
> +    latents = np.array([np.convolve(e, impulse_response, mode='full')[:n_time] for e in events])
can use scipy.ndimage.filters.convolve1d to do this all at once instead of in a loop

2017-05-02 00:05 UTC, poolio commented on twpca/datasets.py
> +    readout_weights = np.random.rand(n_neuron) + 0.1
where's this 0.1 come from?

2017-05-02 00:05 UTC, poolio commented on twpca/model.py
> +            progressbar (optional): whether to print a progressbar (default: True)
fix order, sess first, progressbar second

2017-05-02 00:51 UTC, ahwillia commented on twpca/crossval.py
> +def leave_n_out(N, K):
👍

2017-05-02 00:52 UTC, ahwillia commented on twpca/crossval.py
> +    idx = np.arange(N)
I was back and forth about which would be better. If we're doing this over multiple hyperparams we might want the same random permutation... I think I'll fix by passing a seed.

2017-05-03 21:42 UTC, ahwillia commented on twpca/crossval.py
> +def k_fold(N, K):
done.

2017-05-03 21:42 UTC, ahwillia commented on twpca/crossval.py
> +    idx = np.arange(N)
done.

2017-05-03 21:42 UTC, ahwillia commented on twpca/crossval.py
> +    idx = np.arange(N)
done.

2017-05-03 21:44 UTC, ahwillia commented on twpca/crossval.py
> +        K: int, crossvalidation parameter
done.

2017-05-03 21:44 UTC, ahwillia commented on twpca/crossval.py
> +        traindata = np.atleast_3d(data[:, :, train])
Nope, good catch.

2017-05-03 21:44 UTC, ahwillia commented on twpca/crossval.py
> +        tf.reset_default_graph()
done.

2017-05-03 21:45 UTC, ahwillia commented on twpca/crossval.py
> +        # TODO - warmstart fits?
deleted.

2017-05-03 21:46 UTC, ahwillia commented on twpca/crossval.py
> +    for nc, ws, ts in zip(tqdm(n_components), warp_scales, time_scales):
strangely enough it does seem to work. But replaced with `trange`

2017-05-03 21:47 UTC, ahwillia commented on twpca/datasets.py
> +    latents = np.array([np.convolve(e, impulse_response, mode='full')[:n_time] for e in events])
done.

2017-05-03 21:48 UTC, ahwillia commented on twpca/datasets.py
> +    readout_weights = np.random.rand(n_neuron) + 0.1
deleted.

2017-05-03 21:48 UTC, ahwillia commented on twpca/model.py
> +            progressbar (optional): whether to print a progressbar (default: True)
done.

2017-05-03 21:50 UTC, ahwillia commented on twpca/crossval.py
> +        _, resid, _, _ = np.linalg.lstsq(time_factors, testdata.reshape(-1, len(test)))
`transform()` applies the warps. Do you want me to make `model.apply()`?

2017-05-03 21:50 UTC, ahwillia commented on twpca/crossval.py
> +             'test_error': np.sum(resid) / len(testdata.ravel()),
Yes, but perhaps better to put this inside the model class.

2017-05-03 22:04 UTC, ahwillia commented on twpca/crossval.py
> +    for nc, ws, ts in zip(tqdm(n_components), warp_scales, time_scales):
Ah my bad - `n_components` is actually passed in as a list. See the updated docstring.

2017-05-05 18:55 UTC, ahwillia commented
@poolio - ready to review again.

2017-05-06 00:22 UTC, poolio requested changes
a few more minor changes to the code. almost there :)

2017-05-06 00:22 UTC, poolio commented on twpca/datasets.py
> +    latents = np.array([np.convolve(e, impulse_response, mode='full')[:n_time] for e in events])
it looks like you imported but still aren't using convolve1d

2017-05-06 00:22 UTC, poolio commented on twpca/model.py
> +
can you add docstring for the expected size of X and a check that the size of X matches the temporal factors

2017-05-06 00:22 UTC, poolio commented on twpca/crossval.py
> +    """Compares vanilla PCA to twPCA searching over number of components
add docstring for args/returns

2017-05-06 00:22 UTC, poolio commented on twpca/crossval.py
> +
can you document somewhere how the keywoard arguments are combined? typically these kind of functions take the outer product over all parameters, but here you're taking them both in as lists of parameter settings to try

2017-05-07 00:23 UTC, ahwillia commented on twpca/crossval.py
> +    """Compares vanilla PCA to twPCA searching over number of components
This isn't exported. I'm still playing with the functionality I want - will remove for now.

2017-05-07 00:30 UTC, ahwillia commented on twpca/model.py
> +
done

2017-05-07 00:30 UTC, ahwillia commented on twpca/crossval.py
> +
Sort of verbose but the docstring has an example use case

2017-05-07 02:59 UTC, merged